### ISSUE TITLE
Upgrade to the latest HeidiSQL version

### ISSUE THREAD

**Issue by Ivan-Perez** [Kianda/heidisql-snap#4]
As of today, HeidiSQL has released [version 12.5](https://www.heidisql.com/download.php), whereas this snap package is stuck at 12.1.

I'd be glad to create a pull request to upgrade HeidiSQL, but there are no instructions in the repository on how to get it.

Thank you!

**Comment by MarosPixel** [comment]
Hello @Kianda, I would like to help with building and releasing of a new version. A was able to build 12.8 version, but I don't have rights to upload it into snapstore. Please let me know.

**Comment by Kianda** [comment]
Hi, I will trigger a new build asap, if you made any changes to the code just make a pull request! ^^

**Comment by MarosPixel** [comment]
No changes were necessary.

**Comment by Ivan-Perez** [comment]
Thank you very much!! 
![image](https://github.com/user-attachments/assets/10d05a0e-dd02-497c-96c0-653113cd4b21)
